#'Wrapper to estimate model-agnostic variable importance for multi-response models. 
#'@param yhats A \code{list} is the list generated by mrIMLpredicts
#'@param X  A \code{dataframe} is the feature data 
#'@details Calculates variable importance using based on partial dependencies but could do permutations as well (more memory intensive).
#' Key input is the object created by MrIML. Can be plotted with the plot_vi function.
#' @example 
#' VI <- mrVip(yhats, X=X)
#' groupCov <- c(rep ("Host_characteristics", 1),rep("Urbanisation", 3), rep("Vegetation", 2), rep("Urbanisation",1), rep("Spatial", 2), 
#' rep('Host_relatedness', 6),rep ("Host_characteristics", 1),rep("Vegetation", 2), rep("Urbanisation",1))  
#' plot_vi(VI=VI,  X=X,Y=Y, modelPerf=ModelPerf, groupCov, cutoff= 0.5)
#'@export 

mrCoOccurNet_bootstrap <- function(mrPD_obj, Y){   #,  variable ='Plas
  
  n_response <- length(Y)
  
  mrPD_obj <- mrPD_obj[[1]] #dont want the plot
  
  PD_yList <- mrPD_obj[seq_along(Y)] #just keep the taxa
  
  result_final_df <- list()
  
  #cooccur_list <- #lapply(PD_yList, function(i){
  for (i in seq_along(PD_yList)) {
    
    #extract data for each variable in the models
    df <-  PD_yList [[i]]
    
    #calculate the standard deviation of each bootstrap for each taxa
    
    df1 <- df %>% mutate(predictor=names(df[1])) %>% 
      rename(class = 1)
    
    result_sd <- df1 %>%
      group_by(target, bootstrap) %>%
      summarize(sd_value = sd(value)) %>% 
      group_by(target) %>% 
      summarize(mean_strength = mean(sd_value), lower_ci = quantile(sd_value, probs = 0.025), upper_ci = quantile(sd_value, probs = 0.975)) %>% 
      mutate(predictor=df1$predictor[1])
    
    
    result_final <- df1 %>%
      spread(class, value) %>%
      mutate(direction = `1` - `0`) %>% 
      group_by(target) %>% 
      summarize(mean_direction=mean(direction)) %>% 
      mutate(direction = ifelse(mean_direction > 0, "positive", "negative")) %>% 
      right_join(result_sd, by='target')
    
    result_final_df[[i]] <- result_final
    
    
  }
  
  complete_net <- do.call(rbind,result_final_df) 
  
  complete_network <- complete_net %>%  rename(taxa_1=target,taxa_2= predictor) %>% 
    select(taxa_1, taxa_2, direction, mean_strength, lower_ci, upper_ci, mean_direction)
  
  return(complete_network)
  
}












