#'mrFlashlight:  Wrapper to plot mutlti-response model agnostic partial dependency plots. 
#.
#'@param yhats A \code{list} is the list generated by mrIMLpredicts
#'@param X A \code{dataframe} is a response variable data set (species, OTUs, SNPs etc)
#'@param Y  A \code{dataframe} #is the feature dataset
#'@param response \code{character} 'single' selects one response, 'multi' selects all responses
#'@param index \code{numeric} selects which response to create a flaslight object for. Only used when 'single' is selcted. The order is the same as 'X'.
#'
#'
#'@details The aim of this function is to enable users to ustilize interpretable machine learning methods
#'to understand their multi-response and single response models
#' 
#' @example 
#' #single response
#' fl <- mrFlashlight(yhats, X, Y, response = "single", index=1)
#'
#'plot(light_performance(fl), fill = "orange") + labs(x = element_blank())
#'
#'plot(light_breakdown(fl , new_obs = cbind(X, Y)[1, ]),by = X, v=Y) #prints all responses - need to fix but could be quite handy.
#'
#'int <- light_interaction(fl, pairwise=TRUE) #not working, but possible!
#'
#'Multiple response
#' flashlightObj <- mrFlashlight(yhats, X, Y, response = "multi")


mrFlashlight <- function (yhats, X, Y, response = "multi", index=1){
    
    
    # Prediction function
    
    pred_fun <- function(m, dat) {
      
      predict(
        
        m,
        
        data.matrix(dat[, colnames(Y), drop = FALSE]),
        
        type = "prob"
        
      )[[".pred_1"]]
      
    }
    
    
    
    # List of metrics
    
    metrics = list(
      
      logloss = MetricsWeighted::logLoss,
      
      `ROC AUC` = MetricsWeighted::AUC,
      
      `% Dev Red` = MetricsWeighted::r_squared_bernoulli
      
    )
    
 
    #any predict function
    
    if(response == 'single'){
    
    
    
    mfl <- flashlight(
      
      model = yhats[[index]]$mod1_k, #change the index to focus on other SNPs
      
      label = colnames(X)[index],
      
      data = cbind(Y, X),
      
      y = colnames(X)[index],
      
      predict_function = pred_fun,
      
      metrics = metrics
    )

    }
    

  if(response == 'multi'){

    # Multiple responses
    
    models <- lapply(yhats, `[[`, "mod1_k")
    
    
    
    fl_list <- vector("list", length(yhats))
    
    for (i in seq_along(fl_list)) {
      
      fl_list[[i]] <- flashlight(
        
        model = yhats[[i]]$mod1_k,
        
        label = colnames(X)[i],
        
        y = colnames(X)[i]
        
      )
      
    }
    
    
    
    mfl <- multiflashlight(
      
      fl_list,
      
      data = cbind(Y, X),
      
      predict_function = pred_fun,
      
      metrics = metrics
      
    )
    
  }
    return( mfl)
}
    
    
    
    
  