#'mrFlashlight:  Wrapper to plot mutlti-response model agnostic partial dependency plots. 
#.
#'@param yhats A \code{list} is the list generated by mrIMLpredicts
#'@param X A \code{dataframe} is a response variable data set (species, OTUs, SNPs etc)
#'@param Y  A \code{dataframe} #is the feature dataset
#'@param Model 1 A \code{list} can be any model from the tidy model package. See examples.
#'@param 'Feature' \code{character} Feature from the Y set to plot the partial dependency.
#'
#'@details The aim of this function is to enable users to calculate partial dependencies for the response variables for each model (i.e. species/SNPs)
#' and then use plot_mrpd (a plotting function) to create a pd plot for all species/SNPs for each feature. 
#' Could build functionality for ICE plots but that would be messy for multiple repsonse variables.
#' 
#' @example 
#' testPdp <- mrPdP(yhats, model1,X=X,Y=Y)


mrFlashlight <- function (yhats, X, Y, response = "multi", index=1){
    
    
    # Prediction function
    
    pred_fun <- function(m, dat) {
      
      predict(
        
        m,
        
        data.matrix(dat[, colnames(Y), drop = FALSE]),
        
        type = "prob"
        
      )[[".pred_1"]]
      
    }
    
    
    
    # List of metrics
    
    metrics = list(
      
      logloss = MetricsWeighted::logLoss,
      
      `ROC AUC` = MetricsWeighted::AUC,
      
      `% Dev Red` = MetricsWeighted::r_squared_bernoulli
      
    )
    
 
    #any predict function
    
    if(response == 'single'){
    
    
    
    mfl <- flashlight(
      
      model = yhats[[index]]$mod1_k, #change the index to focus on other SNPs
      
      label = colnames(X)[index],
      
      data = cbind(Y, X),
      
      y = colnames(X)[index],
      
      predict_function = pred_fun,
      
      metrics = metrics
    )

    }
    

  if(response == 'multi'){

    # Multiple responses
    
    models <- lapply(yhats, `[[`, "mod1_k")
    
    
    
    fl_list <- vector("list", length(yhats))
    
    for (i in seq_along(fl_list)) {
      
      fl_list[[i]] <- flashlight(
        
        model = yhats[[i]]$mod1_k,
        
        label = colnames(X)[i],
        
        y = colnames(X)[i]
        
      )
      
    }
    
    
    
    mfl <- multiflashlight(
      
      fl_list,
      
      data = cbind(Y, X),
      
      predict_function = pred_fun,
      
      metrics = metrics
      
    )
    
  }
    return( mfl)
}
    
    
    
    
  