#'Converts MrIML objects into a format suitable for IML R package
#'@param yhats A \code{list} is the list generated by mrIMLpredicts
#'@param mode \code{character}'classification' or 'regression' i.e., is the generative model a regression or classification?
#'@details This function is a wrapper to convert MrIML objects into the IML R package format (Molnar and Schratz, 2021)
#'
#'@example
#'yhats<- mrIMLpredicts(X=X,Y=Y, model1=model1, balance_data='no', model='classification') 
#'mrIMLconverts_list <- MrIMLconverts(yhats, X, mode='classification')
#'\dontrun{
#'
#'@export 
#'

MrIMLconverts <- function (yhats, X,  mode='regression'){
  n_response<- length(yhats) ###

#extract model for each response
  modList <- yhats %>% purrr::map(pluck('mod1_k')) #extracts model ###

#extracts data from each model
  Datalist <- yhats %>% purrr::map(pluck('data'))

  im <- lapply(seq(1:n_response), function(i){ 
   mod <- modList[[i]]%>%  ###
     pull_workflow_fit()

    # # if (mode=='regression'){
    #   pred <- Predictor$new(mod, data=X, y=Datalist[[i]]$class) ##
    # 
    #   #imp <- FeatureImp$new(pred , loss = "mae")
    #   #plot(imp)
    
    if (mode=='classification'){
      
      #create a IML predictor variable for each response
      pred <- Predictor$new(mod, data=X, y=Datalist[[i]]$class, type="prob")
      
      }
        else { pred <- Predictor$new(mod, data=X, y=Datalist[[i]]$class)}
  
  })

}

#other predict functions if needed
# pred_fun <- function(m, dat) {
#   
#   predict(
#     
#     m, dat[, colnames(X), drop = FALSE],
#     
#     #data.matrix(dat[, colnames(Y), drop = FALSE]),
#     
#     type = "prob"
#     
#   )[[".pred_1"]]}
# 
# predict_wrapper2 <- function(model, newdata){
#   predict(object = model, new_data = newdata)
# }


