#'mrInteractions:  Wrapper to calculate and plot summed interactions of features across response variables 
#.
#'@param yhats A \code{list} is the list generated by mrIMLpredicts
#'@param X A \code{dataframe} is a response variable data set (species, OTUs, SNPs etc)
#'@param Y  A \code{dataframe} #is the feature dataset
#'@param Model 1 A \code{list} can be any model from the tidy model package. See examples.
#'@param 'Feature' \code{character} Feature from the Y set to plot the partial dependency.
#'
#'@details The aim of this function is to enable users to calculate partial dependencies for the response variables for each model (i.e. species/SNPs)
#' and then use plot_mrpd (a plotting function) to create a pd plot for all species/SNPs for each feature. 
#' Could build functionality for ICE plots but that would be messy for multiple repsonse variables.
#' 
#' @example 
#' testPdp <- mrPdP(yhats, model1,X=X,Y=Y)


mrInteractions <- function(yhats, X, Y){
  
  l_response<- length(yhats)
  n_features <- names(Y)
  n_response <- names(X)
  
  #unpack everything from yhats
  tList <- yhats %>% purrr::map(pluck('data_train')) #get together training data.
  modList <- yhats %>% purrr::map(pluck('mod1_k'))
  dataAll <- yhats %>% purrr::map(pluck('data'))
  fitList <- yhats %>% purrr::map(pluck('last_mod_fit'))

  
    interact <- vintMR(int, feature_names = names(Y), train = tList[[1]], n.trees =100)
    #modified vint function - very slow over171 combinations
    
    # Plot top 20 results
 top_20 <- interact[1L:20L, ]
 
ggplot(top_20, aes(x = reorder(Variables, Interaction), y = Interaction)) +
     geom_col() +
    coord_flip() +
    xlab("") +
    ylab("Interaction strength")
     }
    
    # Create a model object
    mod <- Predictor$new(int, data = dataAll[[1]][-which(names(dataAll[[1]]) == "class")])
    
    # Measure the interaction strength
    ia <- Interaction$new(mod)
    
    # Plot the resulting leaf nodes
    plot(ia)  
    
  })
  
  ImpGlobal <- do.call(cbind, im) 