#'mrPdP:  Wrapper to plot mutlti-response model agnostic partial dependency plots. 
#.
#'@param yhats A \code{list} is the list generated by mrIMLpredicts
#'@param X A \code{dataframe} is a response variable data set (species, OTUs, SNPs etc)
#'@param Y  A \code{dataframe} #is the feature dataset
#'@param Model 1 A \code{list} can be any model from the tidy model package. See examples.
#'
#'@details The aim of this function is to enable users to calculate partial dependencies for the response variables for each model (i.e. species/SNPs)
#' and then use plot_mrpd (a plotting function) to create a pd plot for all species/SNPs for each feature. 
#' Could build functionality for ICE plots but that would be messy for multiple repsonse variables.
#' 
#' @example 
#' testPdp <- mrPdP(yhats, model1,X=X,Y=Y) #doesn't work with mutliple features yet.


mrPdP <- function(yhats, model1, X, Y){
  
  l_response<- length(yhats)
  n_features <- names(Y)
  n_response <- names(X)
  
  #unpack everything from yhats
  mList <- yhats %>% purrr::map(pluck('last_mod_fit'))
  tList <- yhats %>% purrr::map(pluck('data_train')) #get together training data.
  dList <- yhats %>% purrr::map(pluck('data')) #get together training data.
  
  
  pdI <- NULL #create empty datafram for pd values
  
  for (i in 1:l_response){ #went with a for loop as I was having problems naming columns/rows
    
    p <-  mList[[i]] %>% 
      purrr::pluck(".workflow",1) %>%   # I like tidy model workflows but it is annoying to extract fits like this
      pull_workflow_fit() 
    
    pred_prob <- function(object, newdata) { # had to add this as pdp doesn't like tidymodel new_data call 
      c<- predict(p, new_data=tList[[i]], type = "prob")[,2]# [,2} selects postive yhats (change to 1 for negative class). 
      mean(c$.pred_1, drop = TRUE) #drop=T removes NAs.
    }
      #mean makes it a pd rather than ICE. ICE would be impossible to see for the global plot but we could add
      #it for the individual model plots
  
    #need to add for all features
    
    #currently with the bocat FIV data (multiple features) this isn't working.
    
    #Get the error: Error in rep.int(rep.int(seq_len(nx), rep.int(rep.fac, nx)), orep) : 
     # invalid 'times' value
    #
     pdI[[i]] <- partial(p, pred.var = n_features, train = tList[[i]],  type = c("classification"), pred.fun = pred_prob)
     
     names(pdI[[i]])[2] <-  n_response[i]
     
     as.data.frame(pdI)

     #then the idea is to plot the yhat values for each response for each Y
}

   PdpGlobal <- do.call(cbind, pdI) 
   
   return(PdpGlobal)#just need to get the response names to be the column names. maybe for loop here instead of lapply
}   
# values seem odd in that in the coinfection example scale prop. zos has no impact on 
