#'Wrapper to estimate model-agnostic variable importance for multi-response models. 
#'@param yhats A \code{list} is the list generated by mrIMLpredicts
#'@param Y  A \code{dataframe} #is the feature dataset
#'@details Calculates variabie importance using based on partial dependencies but could do permutation as well (mor memory intensive).
#' Key imput is the object created by MrIML. Can be plotted with the plot_vi function.
#' @example 
#' VI <- mrVip(yhats, Y=Y)
#'groupCov <- c(rep ("Host_characteristics", 1),rep("Urbanisation", 3), rep("Vegetation", 2), rep("Urbanisation",1), rep("Spatial", 2), 
#'rep('Host_relatedness', 6),rep ("Host_characteristics", 1),rep("Vegetation", 2), rep("Urbanisation",1))  
#'plot_vi(VI=VI,  X=fData,Y=FeaturesnoNA, modelPerf=ModelPerf, groupCov, cutoff= 0.5)
#'@export

mrVip <- function (yhats, Y){ 
  
  n_response<- length(yhats)
  n_features <- sort(names(Y))
  
  modList <- yhats %>% purrr::map(pluck('mod1_k')) #extracts model
  
   im <- lapply(seq(1:n_response), function(i){ #uses monte carlo CV
     imp <- modList[[i]]%>% 
     
     pull_workflow_fit()
     
    #imp$fit$coefficients[is.na( imp$fit$coefficients)]=0 #for GLMs on the bocat data I get 0 coefficents/residuals etc which are problematic. This still doesn't work. Brandon any ideas how to make VIP work on all features even those with 0 coefficents?
    
     #impVI <- vip(imp,plot=FALSE, num_features=length(Y)) 
     impVI <- vip(imp, num_features=length(Y)) 
    impD <- impVI$data %>% 
      arrange(Variable)%>% 
      purrr::pluck("Importance")
 })
 
  ImpGlobal <- do.call(cbind, im) 
  
 
 #return(ImpGlobal)
}